// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyCTaoTyv804Jwb1Fx9qRTGjLD79UJRjM',
    appId: '1:987743532779:web:c0ddcc58eef1d2dfae70ae',
    messagingSenderId: '987743532779',
    projectId: 'barcodeappalert',
    authDomain: 'barcodeappalert.firebaseapp.com',
    storageBucket: 'barcodeappalert.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIlfHOqN1bF0XzrrYmNn5M69wKTV8hP9g',
    appId: '1:987743532779:android:b430ec1ba2d6a8e3ae70ae',
    messagingSenderId: '987743532779',
    projectId: 'barcodeappalert',
    storageBucket: 'barcodeappalert.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAA728y-_9ueCJZnR8JQXKHKocPfBNWggg',
    appId: '1:987743532779:ios:374a0872a10dde1eae70ae',
    messagingSenderId: '987743532779',
    projectId: 'barcodeappalert',
    storageBucket: 'barcodeappalert.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAA728y-_9ueCJZnR8JQXKHKocPfBNWggg',
    appId: '1:987743532779:ios:374a0872a10dde1eae70ae',
    messagingSenderId: '987743532779',
    projectId: 'barcodeappalert',
    storageBucket: 'barcodeappalert.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyCTaoTyv804Jwb1Fx9qRTGjLD79UJRjM',
    appId: '1:987743532779:web:70582c9b0aeda5bbae70ae',
    messagingSenderId: '987743532779',
    projectId: 'barcodeappalert',
    authDomain: 'barcodeappalert.firebaseapp.com',
    storageBucket: 'barcodeappalert.firebasestorage.app',
  );

}