// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMvTHAPe4NcXQ-VAkeHsIJD-ypBIQsPn8',
    appId: '1:815829848221:web:f3884ed7459f4e381a0474',
    messagingSenderId: '815829848221',
    projectId: 'appalert-db9d5',
    authDomain: 'appalert-db9d5.firebaseapp.com',
    storageBucket: 'appalert-db9d5.firebasestorage.app',
    measurementId: 'G-329RLWWB8H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8szhp9fYKL5clKgzX-eO4qpuXkfL-1tE',
    appId: '1:815829848221:android:f6f97b6a967697251a0474',
    messagingSenderId: '815829848221',
    projectId: 'appalert-db9d5',
    storageBucket: 'appalert-db9d5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCR96FX7qutPUZj_ypTCIZMSHfUs8HqBQ0',
    appId: '1:815829848221:ios:9640c978a3338dde1a0474',
    messagingSenderId: '815829848221',
    projectId: 'appalert-db9d5',
    storageBucket: 'appalert-db9d5.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCR96FX7qutPUZj_ypTCIZMSHfUs8HqBQ0',
    appId: '1:815829848221:ios:9640c978a3338dde1a0474',
    messagingSenderId: '815829848221',
    projectId: 'appalert-db9d5',
    storageBucket: 'appalert-db9d5.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMvTHAPe4NcXQ-VAkeHsIJD-ypBIQsPn8',
    appId: '1:815829848221:web:39032e77b68b37f41a0474',
    messagingSenderId: '815829848221',
    projectId: 'appalert-db9d5',
    authDomain: 'appalert-db9d5.firebaseapp.com',
    storageBucket: 'appalert-db9d5.firebasestorage.app',
    measurementId: 'G-6VGZGES3PD',
  );
}
